import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowsAlt,
  faArrowUp,
  faAward,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClipboard,
  faClipboardList,
  faEdit,
  faEnvelope,
  faExclamationCircle,
  faFile,
  faFileAlt,
  faHome,
  faInfo,
  faInfoCircle,
  faPaperPlane,
  faPortrait,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faShare
} from "@fortawesome/free-solid-svg-icons";

library.add(faArrowsAlt);
library.add(faArrowUp);
library.add(faAward);
library.add(faCheckCircle);
library.add(faChevronDown);
library.add(faChevronLeft);
library.add(faChevronRight);
library.add(faChevronUp);
library.add(faCircle);
library.add(faClipboard);
library.add(faClipboardList);
library.add(faEdit);
library.add(faEnvelope);
library.add(faExclamationCircle);
library.add(faFile);
library.add(faFileAlt);
library.add(faHome);
library.add(faInfo);
library.add(faInfoCircle);
library.add(faPaperPlane);
library.add(faPortrait);
library.add(faQuestion);
library.add(faQuestionCircle);
library.add(faSearch);
library.add(faShare);
